### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JuZi233** [wangpy1995/dxgi4py#1]
Traceback (most recent call last):
  File ".\dxgi_sample.py", line 20, in <module>
    dxgi.init_dxgi(hwnd)
OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by JuZi233** [comment]
我用VS2022编译生成成功了dll文件也是报这个错，系统是windows10

**Comment by wangpy1995** [comment]
把pch.cpp第52行‘winrt::init_apartment(winrt::apartment_type::multi_threaded);’注释掉应该就解决了

**Comment by JuZi233** [comment]
> 把pch.cpp第52行‘winrt::init_apartment(winrt::apartment_type::multi_threaded);’注释掉应该就解决了

这行没报错，亲测报错是： winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool m_framePool =
	winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool::Create(
		device,
		winrt::Windows::Graphics::DirectX::DirectXPixelFormat::B8G8R8A8UIntNormalized,
		2,
		size);  这一行

**Comment by wangpy1995** [comment]
应该是运行环境问题,是不是vc环境没装完

**Comment by haochen97** [comment]
我也遇到了同样的问题，重装了VC环境依然不行

**Comment by haochen97** [comment]
> > 把pch.cpp第52行‘winrt::init_apartment(winrt::apartment_type::multi_threaded);’注释掉应该就解决了
> 
> 这行没报错，亲测报错是： winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool m_framePool = winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool::Create( device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat::B8G8R8A8UIntNormalized, 2, size); 这一行

大哥最后解决了吗

**Comment by JuZi233** [comment]
> > > 把pch.cpp第52行‘winrt::init_apartment(winrt::apartment_type::multi_threaded);’注释掉应该就解决了
> > 
> > 
> > 这行没报错，亲测报错是： winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool m_framePool = winrt::Windows::Graphics::Capture::Direct3D11CaptureFramePool::Create( device, winrt::Windows::Graphics::DirectX::DirectXPixelFormat::B8G8R8A8UIntNormalized, 2, size); 这一行
> 
> 大哥最后解决了吗

没有，我自己搓了个新的，亲测在任意其它电脑都能正常运行
