### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by pdc523** [wangpy1995/dxgi4py#6]
我用你的示例脚本测试了一下，发现截取一次差不多一秒，而正常使用dxgi截图一般都是希望性能最大化，到1ms左右，是性能本来就这样还是我的打开方式不对？没看c++代码，直接调用的dll

**Comment by MeGumisn** [comment]
image = np.fromiter(buffer, dtype=np.uint8, count=height * width * 4).reshape((height, width, 4))

**Comment by pdc523** [comment]
能不能dll返回一个指向图像数据的指针，然后直接通过指针读取

**Comment by MeGumisn** [comment]
返回的buffer里就是BGRA图像数据

**Comment by q2547978337** [comment]
能否出32位

**Comment by pdc523** [comment]
哦，原来你这个函数和我之前搞得一样，是返回的指向图像数据的指针，那直接这样就行了，对性能基本无损，image = np.ctypeslib.as_array(buffer, shape=(1080, 1920, 4))，我的比较吃显卡的游戏里运行时间很长，有时候能达到10ms，所以来github上找代码，你这个很强，可以做到2ms到6ms跳动

**Comment by pdc523** [comment]
你可以将例子代码修改一下，就用这个api，性能是正常的

**Comment by wangpy1995** [comment]
> 能否出32位

已加

**Comment by pdc523** [comment]
你这个库会和decam冲突，如果导入了decam库就会导致你的初始化那个函数报错

**Comment by wangpy1995** [comment]
> 你这个库会和decam冲突，如果导入了decam库就会导致你的初始化那个函数报错

dxcam用了win32com库，底层依赖问题，解决不了
